// dns for server error
import { setServers } from "node:dns/promises";
setServers(["1.1.1.1", "8.8.8.8"]);

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata = {
	title: "SkillSwap",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			data-theme="light"
			className={`h-full antialiased`}
		>

			<body className={`${inter.className} min-h-full flex flex-col`}>
				<Navbar />
				{children}</body>
		</html>
	);
}
